version: 1.0.{build}
image: Visual Studio 2017
configuration: Debug
platform: Any CPU
environment:
  _SkipNearestTargetFrameworkResolution: true
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test_script:
- cmd: >-
    cd IPAddressRange.Test.Core

    dotnet test

    cd ..\IPAddressRange.Test\bin\Debug

    vstest.console /logger:Appveyor IPRange.Test.dll
